services:
  web:
    build: .
    container_name: web_prod_portfolio_backend
    restart: always
    command: bash compose/prod/entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8003:8003
    env_file:
      - .env