# Generated by Django 5.2.3 on 2025-06-26 09:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', tinymce.models.HTMLField(verbose_name='Информация')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Mail')),
                ('sender_message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=225, verbose_name='Время')),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='Иконки')),
                ('main_info', models.CharField(max_length=255)),
                ('next_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('who_am_i', models.CharField(max_length=255, verbose_name='Кто я')),
                ('focus', models.CharField(max_length=255, verbose_name='Фокус')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='Иконки')),
                ('url_path', models.URLField(verbose_name='URL Дорога')),
            ],
        ),
        migrations.CreateModel(
            name='Skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Изображения')),
                ('links', models.URLField(verbose_name='URL Дорога')),
                ('skils', models.ManyToManyField(related_name='projects', to='portfolio.skils', verbose_name='Скилы')),
            ],
        ),
    ]
