# Generated by Django 5.2.3 on 2025-06-26 09:56

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='info_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='about',
            name='info_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='about',
            name='info_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='experience',
            name='main_info_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='main_info_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='main_info_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='next_info_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='next_info_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='next_info_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='focus_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Фокус'),
        ),
        migrations.AddField(
            model_name='home',
            name='focus_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Фокус'),
        ),
        migrations.AddField(
            model_name='home',
            name='focus_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Фокус'),
        ),
        migrations.AddField(
            model_name='home',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='home',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='home',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_am_i_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Кто я'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_am_i_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Кто я'),
        ),
        migrations.AddField(
            model_name='home',
            name='who_am_i_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Кто я'),
        ),
        migrations.AddField(
            model_name='projects',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='projects',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='projects',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='skils',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='skils',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия'),
        ),
        migrations.AddField(
            model_name='skils',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия'),
        ),
    ]
