# Generated by Django 5.2.3 on 2025-06-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about_info_en_about_info_ru_about_info_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('icon', models.ImageField(upload_to='icons/', verbose_name='Иконки')),
                ('url_path', models.URLField(verbose_name='URL Дорога')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Названия')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Названия')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Названия')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('content_en', models.TextField(null=True, verbose_name='Контент')),
                ('content_uz', models.TextField(null=True, verbose_name='Контент')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Изображения')),
                ('links', models.URLField(verbose_name='URL Дорога')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Названия')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Названия')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Названия')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Названия')),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.AddField(
            model_name='project',
            name='skils',
            field=models.ManyToManyField(related_name='projects', to='portfolio.skill', verbose_name='Скилы'),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Skils',
        ),
    ]
