# Generated by Django 5.2.3 on 2025-06-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_link_project_skill_delete_links_project_skils_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
