# Generated by Django 5.2.3 on 2025-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='cv/', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Обо мне', 'verbose_name_plural': 'Обо мне'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт', 'verbose_name_plural': 'Опыт'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='links',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skils',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default=1, verbose_name='Ссылка на проект'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='portfolio.skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sender_email',
            field=models.EmailField(max_length=254, verbose_name='Email отправителя'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_info',
            field=models.CharField(max_length=255, verbose_name='Основная информация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_info_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Основная информация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_info_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Основная информация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_info_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Основная информация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='next_info',
            field=models.CharField(max_length=255, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='next_info_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='next_info_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='next_info_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='time',
            field=models.CharField(max_length=225, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Навык'),
        ),
    ]
