# Generated by Django 5.2.3 on 2025-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_cv_alter_about_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действующий'),
        ),
    ]
