# Generated by Django 5.2.3 on 2025-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_cv_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='photo',
            field=models.ImageField(default=1, upload_to='photoes/', verbose_name='Фотографии'),
            preserve_default=False,
        ),
    ]
