# Generated by Django 5.2.3 on 2025-06-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_home_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='time_en',
            field=models.CharField(max_length=225, null=True, verbose_name='Период'),
        ),
        migrations.AddField(
            model_name='experience',
            name='time_ru',
            field=models.CharField(max_length=225, null=True, verbose_name='Период'),
        ),
        migrations.AddField(
            model_name='experience',
            name='time_uz',
            field=models.CharField(max_length=225, null=True, verbose_name='Период'),
        ),
    ]
