# Generated by Django 5.2.3 on 2025-06-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_experience_time_en_experience_time_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='document_en',
            field=models.FileField(null=True, upload_to='cv/', verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='cv',
            name='document_ru',
            field=models.FileField(null=True, upload_to='cv/', verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='cv',
            name='document_uz',
            field=models.FileField(null=True, upload_to='cv/', verbose_name='Резюме'),
        ),
    ]
